name: t2p_vendor
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  country_flags: ^2.2.0
  get: ^4.6.6
  gap: ^3.0.1
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  flutter_otp_text_field: ^1.1.1
  timer_count_down: ^2.2.2
  connectivity_plus: ^5.0.2
  pretty_dio_logger: ^1.2.0-beta-1
  dio: ^5.4.0
  firebase_core: ^2.30.0
  flutter_widget_from_html: ^0.14.11
  firebase_crashlytics: ^3.3.1
  firebase_messaging: ^14.6.2
  firebase_analytics: ^10.4.5
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
