// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb0GFBI8anhuIiG1za7HMO4IlTf3CV39k',
    appId: '1:569149647523:web:d45b4e84541e550344ed16',
    messagingSenderId: '569149647523',
    projectId: 'taste2plate-1be43',
    authDomain: 'taste2plate-1be43.firebaseapp.com',
    databaseURL: 'https://taste2plate-1be43-default-rtdb.firebaseio.com',
    storageBucket: 'taste2plate-1be43.appspot.com',
    measurementId: 'G-JXJ8SYTZ2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe_TB4tSHMVBT2weqw74MR5-EHZZ4HBnc',
    appId: '1:569149647523:android:e7aaffc28923a2b744ed16',
    messagingSenderId: '569149647523',
    projectId: 'taste2plate-1be43',
    databaseURL: 'https://taste2plate-1be43-default-rtdb.firebaseio.com',
    storageBucket: 'taste2plate-1be43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7w3QbWn-pczgk4q4XyBbmaCeA4Sn-e2I',
    appId: '1:569149647523:ios:331b14ff8164808444ed16',
    messagingSenderId: '569149647523',
    projectId: 'taste2plate-1be43',
    databaseURL: 'https://taste2plate-1be43-default-rtdb.firebaseio.com',
    storageBucket: 'taste2plate-1be43.appspot.com',
    androidClientId: '569149647523-bajhet2ktm7e3sug9c3t8mm7q17qsh4v.apps.googleusercontent.com',
    iosClientId: '569149647523-n700rvgtn0v7nu0s1apkvcs9fsv3p7fs.apps.googleusercontent.com',
    iosBundleId: 'taste2plate.app.customers',
  );
}
