// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcs1Gm_zXyNH3KC8_ZR-3V154G9N1VbC4',
    appId: '1:453966502673:web:9a27d43876485919bb4ab0',
    messagingSenderId: '453966502673',
    projectId: 'a-2-a-9f121',
    authDomain: 'a-2-a-9f121.firebaseapp.com',
    databaseURL: 'https://a-2-a-9f121-default-rtdb.firebaseio.com',
    storageBucket: 'a-2-a-9f121.appspot.com',
    measurementId: 'G-QQCDH24S1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEZrLgH6C2hit6yLBqbEpRBgL9tgVspHI',
    appId: '1:453966502673:android:321719bf4e544358bb4ab0',
    messagingSenderId: '453966502673',
    projectId: 'a-2-a-9f121',
    databaseURL: 'https://a-2-a-9f121-default-rtdb.firebaseio.com',
    storageBucket: 'a-2-a-9f121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmjiGGelDEI8_MwRQ49FhdNBJIrpJswmM',
    appId: '1:453966502673:ios:df9f651261af71e7bb4ab0',
    messagingSenderId: '453966502673',
    projectId: 'a-2-a-9f121',
    databaseURL: 'https://a-2-a-9f121-default-rtdb.firebaseio.com',
    storageBucket: 'a-2-a-9f121.appspot.com',
    androidClientId: '453966502673-6d0e8dvvvmidafuu1lph32eh388u1pld.apps.googleusercontent.com',
    iosBundleId: 'com.anything2anyplace.a2a.vendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmjiGGelDEI8_MwRQ49FhdNBJIrpJswmM',
    appId: '1:453966502673:ios:df9f651261af71e7bb4ab0',
    messagingSenderId: '453966502673',
    projectId: 'a-2-a-9f121',
    databaseURL: 'https://a-2-a-9f121-default-rtdb.firebaseio.com',
    storageBucket: 'a-2-a-9f121.appspot.com',
    androidClientId: '453966502673-6d0e8dvvvmidafuu1lph32eh388u1pld.apps.googleusercontent.com',
    iosBundleId: 'com.anything2anyplace.a2a.vendor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcs1Gm_zXyNH3KC8_ZR-3V154G9N1VbC4',
    appId: '1:453966502673:web:1bb6db62b6cc3499bb4ab0',
    messagingSenderId: '453966502673',
    projectId: 'a-2-a-9f121',
    authDomain: 'a-2-a-9f121.firebaseapp.com',
    databaseURL: 'https://a-2-a-9f121-default-rtdb.firebaseio.com',
    storageBucket: 'a-2-a-9f121.appspot.com',
    measurementId: 'G-C35CELSBQL',
  );

}